"""
Code Generation Tasks
"""
import os
import yaml
import json

def create_generate_playwright_code_task(
    agent, 
    test_case_id: str, 
    test_case_title: str, 
    test_steps: list, 
    expected_results: list,
    recorded_flow_json: str = None
):
    """Create task for generating Playwright code"""
    from crewai import Task
    
    yaml_path = os.path.join(os.path.dirname(__file__), 'task.yaml')
    with open(yaml_path, 'r') as file:
        config = yaml.safe_load(file)['generate_playwright_code']
    
    # Format test steps and expected results
    steps_text = "\n".join([f"  {step}" for step in test_steps]) if test_steps else "No steps provided"
    expected_text = "\n".join([f"  {result}" for result in expected_results]) if expected_results else "No expected results provided"
    
    # Load recorded flow if provided
    recorded_flow_text = ""
    if recorded_flow_json and os.path.exists(recorded_flow_json):
        try:
            with open(recorded_flow_json, 'r', encoding='utf-8') as f:
                recorded_data = json.load(f)
                
                # PRIORITY 1: Use the actual codegen generated code (most accurate)
                generated_code = recorded_data.get("generated_code", {})
                python_code = generated_code.get("python", "")
                javascript_code = generated_code.get("javascript", "")
                
                if python_code and python_code.strip():
                    # This is the actual codegen output - use it directly
                    # Note: python_code might actually be JavaScript (codegen output format)
                    flow_lines = []
                    flow_lines.append("=== ACTUAL PLAYWRIGHT CODEGEN OUTPUT (USE THIS FOR LOCATORS) ===")
                    flow_lines.append("")
                    flow_lines.append("CRITICAL: The following is the EXACT code generated by Playwright codegen.")
                    flow_lines.append("This code contains ALL the actual working locators and interactions.")
                    flow_lines.append("YOU MUST extract locators from this code and use them in your POM implementation.")
                    flow_lines.append("")
                    
                    # Determine if it's Python or JavaScript
                    is_javascript = "import {" in python_code or "require('@playwright/test')" in python_code or "const {" in python_code
                    code_lang = "javascript" if is_javascript else "python"
                    
                    flow_lines.append(f"Codegen Code ({code_lang}):")
                    flow_lines.append(f"```{code_lang}")
                    flow_lines.append(python_code.strip())
                    flow_lines.append("```")
                    
                    if javascript_code and javascript_code.strip() and javascript_code != python_code:
                        flow_lines.append("")
                        flow_lines.append("JavaScript Code from Codegen:")
                        flow_lines.append("```javascript")
                        flow_lines.append(javascript_code.strip())
                        flow_lines.append("```")
                    
                    flow_lines.append("")
                    flow_lines.append("=== CRITICAL INSTRUCTIONS - READ CAREFULLY ===")
                    flow_lines.append("⚠️⚠️⚠️ DO NOT USE EXAMPLE LOCATORS FROM TASK.YAML ⚠️⚠️⚠️")
                    flow_lines.append("You MUST extract locators from the codegen code shown above, NOT from examples.")
                    flow_lines.append("")
                    flow_lines.append("Step-by-step process:")
                    flow_lines.append("1. Look at the codegen code in the code block above")
                    flow_lines.append("2. Find EVERY locator call: getByRole(), getByTestId(), locator(), getByText(), etc.")
                    flow_lines.append("3. Extract the exact selector/parameters from each call")
                    flow_lines.append("4. Convert to POM format:")
                    flow_lines.append("   - Python: class Locators with attributes")
                    flow_lines.append("   - JavaScript: const locators object with properties")
                    flow_lines.append("5. For getByRole/get_by_role calls, extract both role and name parameters")
                    flow_lines.append("6. Create reusable functions for each action (click, fill, navigate, etc.)")
                    flow_lines.append("7. Follow DRY principles - reuse locators and functions")
                    flow_lines.append("8. Use the EXACT selectors from codegen - DO NOT modify, improve, or replace them")
                    flow_lines.append("9. The codegen selectors are tested and working - preserve them exactly")
                    flow_lines.append("")
                    flow_lines.append("Example locator extraction (FORMAT ONLY - extract YOUR actual locators):")
                    flow_lines.append("  If codegen has: page.getByRole('button', { name: 'Authenticate' })")
                    flow_lines.append("  Then extract: AUTHENTICATE_BUTTON = \"role=button[name='Authenticate']\"")
                    flow_lines.append("  OR use directly in function: await page.get_by_role('button', name='Authenticate').click()")
                    flow_lines.append("")
                    flow_lines.append("⚠️ REMINDER: Extract locators from YOUR codegen code above, NOT from examples! ⚠️")
                    flow_lines.append("")
                    
                    recorded_flow_text = "\n".join(flow_lines)
                else:
                    # FALLBACK: Use actions array if codegen code not available
                    recorded_events = recorded_data.get("actions", recorded_data.get("recorded_events", []))
                    if recorded_events:
                        # Format recorded events for LLM - include ALL events in sequence
                        flow_lines = []
                        flow_lines.append("=== RECORDED BROWSER FLOW (Playwright Codegen) ===")
                        flow_lines.append(f"Starting URL: {recorded_data.get('url', '')}")
                        flow_lines.append("")
                        flow_lines.append("Complete Navigation and Interaction Sequence:")
                        flow_lines.append("")
                        
                        for idx, event in enumerate(recorded_events, 1):
                            event_type = event.get("type", "")
                            selector_info = event.get("selector", {})
                            value = event.get("value", "")
                            url = event.get("url", "")
                            
                            if event_type == "navigate":
                                flow_lines.append(f"{idx}. NAVIGATE: page.goto('{url}')")
                            elif event_type == "click":
                                if isinstance(selector_info, dict):
                                    sel_type = selector_info.get("type", "")
                                    sel_value = selector_info.get("value", "")
                                    if sel_type == "testid":
                                        flow_lines.append(f"{idx}. CLICK: page.get_by_test_id('{sel_value}').click()")
                                    elif sel_type == "role":
                                        sel_name = selector_info.get("name", "")
                                        if sel_name:
                                            flow_lines.append(f"{idx}. CLICK: page.get_by_role('{sel_value}', name='{sel_name}').click()")
                                        else:
                                            flow_lines.append(f"{idx}. CLICK: page.get_by_role('{sel_value}').click()")
                                    elif sel_type == "text":
                                        flow_lines.append(f"{idx}. CLICK: page.get_by_text('{sel_value}').click()")
                                    elif sel_type == "id":
                                        flow_lines.append(f"{idx}. CLICK: page.locator('#{sel_value}').click()")
                                    elif sel_type == "name":
                                        flow_lines.append(f"{idx}. CLICK: page.locator('[name=\"{sel_value}\"]').click()")
                                    else:
                                        flow_lines.append(f"{idx}. CLICK: {sel_type}={sel_value}")
                            elif event_type == "fill":
                                if isinstance(selector_info, dict):
                                    sel_type = selector_info.get("type", "")
                                    sel_value = selector_info.get("value", "")
                                    if sel_type == "testid":
                                        flow_lines.append(f"{idx}. FILL: page.get_by_test_id('{sel_value}').fill('{value}')")
                                    elif sel_type == "role":
                                        sel_name = selector_info.get("name", "")
                                        if sel_name:
                                            flow_lines.append(f"{idx}. FILL: page.get_by_role('{sel_value}', name='{sel_name}').fill('{value}')")
                                        else:
                                            flow_lines.append(f"{idx}. FILL: page.get_by_role('{sel_value}').fill('{value}')")
                                    elif sel_type == "text":
                                        flow_lines.append(f"{idx}. FILL: page.get_by_text('{sel_value}').fill('{value}')")
                                    elif sel_type == "id":
                                        flow_lines.append(f"{idx}. FILL: page.locator('#{sel_value}').fill('{value}')")
                                    elif sel_type == "name":
                                        flow_lines.append(f"{idx}. FILL: page.locator('[name=\"{sel_value}\"]').fill('{value}')")
                                    else:
                                        flow_lines.append(f"{idx}. FILL: {sel_type}={sel_value} with '{value}'")
                        
                        flow_lines.append("")
                        flow_lines.append("=== END OF RECORDED FLOW ===")
                        flow_lines.append("")
                        flow_lines.append("IMPORTANT: Generate code based on this EXACT sequence. Include ALL navigation steps.")
                        
                        recorded_flow_text = "\n".join(flow_lines)
        except Exception as e:
            print(f"Warning: Could not load recorded flow: {e}")
    
    description = config['description'].format(
        test_case_id=test_case_id,
        test_case_title=test_case_title,
        test_steps=steps_text,
        expected_results=expected_text,
        recorded_flow=recorded_flow_text if recorded_flow_text else "No recorded flow available. Use test steps above."
    )
    
    return Task(
        description=description,
        expected_output=config['expected_output'],
        agent=agent,
        output_file=config.get('output_file')
    )

